
services:
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=cineverso_db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    restart: unless-stopped

#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cineverso_db
#      - SPRING_DATASOURCE_USERNAME=myuser
#      - SPRING_DATASOURCE_PASSWORD=secret
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    depends_on:
#      - db
#    networks:
#      - spring-postgres
#    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - spring-postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
networks:
  spring-postgres:
    driver: bridge
